-- CreateTable
CREATE TABLE "Oil" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SAP" INTEGER NOT NULL,
    "NAOH" REAL NOT NULL,
    "KOH" REAL NOT NULL
);

-- CreateTable
CREATE TABLE "Name" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "oilId" INTEGER NOT NULL,
    "language" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    CONSTRAINT "Name_oilId_fkey" FOREIGN KEY ("oilId") REFERENCES "Oil" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "INCIName" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "oilId" INTEGER NOT NULL,
    "language" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    CONSTRAINT "INCIName_oilId_fkey" FOREIGN KEY ("oilId") REFERENCES "Oil" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
